for i in range(2.0):
    print(i)
# it should give an error
